/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  ApiResponse,
  DeleteObjectParams,
  GetDownloadUrlParams,
  GetListingsParams,
  GetMyFavoritesParams,
  GetMyListingsParams,
  GetMySavedListingsParams,
  Health200,
  ListingCreateRequest,
  ListingResponse,
  ListingUpdateRequest,
  MediaUploadRequest,
  MediaUploadResponse,
  PageListingResponse,
  UserRegistrationRequest,
  UserResponse,
  UserUpdateRequest,
} from './model';

import { customFetch } from './custom-fetch';
/**
 * Creates a user account linked to the authenticated Firebase UID.
 * @summary Register a new user
 */
export type createUserResponse200 = {
  data: ApiResponse;
  status: 200;
};

export type createUserResponseSuccess = createUserResponse200 & {
  headers: Headers;
};
export type createUserResponse = createUserResponseSuccess;

export const getCreateUserUrl = () => {
  return `/users`;
};

export const createUser = async (
  userRegistrationRequest: UserRegistrationRequest,
  options?: RequestInit
): Promise<createUserResponse> => {
  return customFetch<createUserResponse>(getCreateUserUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userRegistrationRequest),
  });
};

/**
 * Generates a pre-signed S3 URL for uploading a file. Returns the URL and the S3 object key.
 * @summary Get a pre-signed upload URL
 */
export type getUploadUrlResponse200 = {
  data: MediaUploadResponse;
  status: 200;
};

export type getUploadUrlResponseSuccess = getUploadUrlResponse200 & {
  headers: Headers;
};
export type getUploadUrlResponse = getUploadUrlResponseSuccess;

export const getGetUploadUrlUrl = () => {
  return `/s3/upload-request`;
};

export const getUploadUrl = async (
  mediaUploadRequest: MediaUploadRequest,
  options?: RequestInit
): Promise<getUploadUrlResponse> => {
  return customFetch<getUploadUrlResponse>(getGetUploadUrlUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(mediaUploadRequest),
  });
};

/**
 * Public endpoint. Returns paginated published listings with optional filters.
 * @summary Search published listings
 */
export type getListingsResponse200 = {
  data: PageListingResponse;
  status: 200;
};

export type getListingsResponseSuccess = getListingsResponse200 & {
  headers: Headers;
};
export type getListingsResponse = getListingsResponseSuccess;

export const getGetListingsUrl = (params: GetListingsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/listings?${stringifiedParams}`
    : `/listings`;
};

export const getListings = async (
  params: GetListingsParams,
  options?: RequestInit
): Promise<getListingsResponse> => {
  return customFetch<getListingsResponse>(getGetListingsUrl(params), {
    ...options,
    method: 'GET',
  });
};

/**
 * Creates a new property listing as draft or published. Requires authentication.
 * @summary Create a listing
 */
export type createListingResponse200 = {
  data: ApiResponse;
  status: 200;
};

export type createListingResponseSuccess = createListingResponse200 & {
  headers: Headers;
};
export type createListingResponse = createListingResponseSuccess;

export const getCreateListingUrl = () => {
  return `/listings`;
};

export const createListing = async (
  listingCreateRequest: ListingCreateRequest,
  options?: RequestInit
): Promise<createListingResponse> => {
  return customFetch<createListingResponse>(getCreateListingUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(listingCreateRequest),
  });
};

/**
 * Saves a listing for later viewing. Returns 409 if already saved.
 * @summary Save a listing
 */
export type saveListingResponse200 = {
  data: ApiResponse;
  status: 200;
};

export type saveListingResponseSuccess = saveListingResponse200 & {
  headers: Headers;
};
export type saveListingResponse = saveListingResponseSuccess;

export const getSaveListingUrl = (id: string) => {
  return `/listings/${id}/save`;
};

export const saveListing = async (
  id: string,
  options?: RequestInit
): Promise<saveListingResponse> => {
  return customFetch<saveListingResponse>(getSaveListingUrl(id), {
    ...options,
    method: 'POST',
  });
};

/**
 * Removes a listing from the authenticated user's saved list. Returns 404 if not saved.
 * @summary Unsave a listing
 */
export type unsaveListingResponse200 = {
  data: ApiResponse;
  status: 200;
};

export type unsaveListingResponseSuccess = unsaveListingResponse200 & {
  headers: Headers;
};
export type unsaveListingResponse = unsaveListingResponseSuccess;

export const getUnsaveListingUrl = (id: string) => {
  return `/listings/${id}/save`;
};

export const unsaveListing = async (
  id: string,
  options?: RequestInit
): Promise<unsaveListingResponse> => {
  return customFetch<unsaveListingResponse>(getUnsaveListingUrl(id), {
    ...options,
    method: 'DELETE',
  });
};

/**
 * Adds a listing to the authenticated user's favorites. Returns 409 if already favorited.
 * @summary Favorite a listing
 */
export type addFavoriteResponse200 = {
  data: ApiResponse;
  status: 200;
};

export type addFavoriteResponseSuccess = addFavoriteResponse200 & {
  headers: Headers;
};
export type addFavoriteResponse = addFavoriteResponseSuccess;

export const getAddFavoriteUrl = (id: string) => {
  return `/listings/${id}/favorite`;
};

export const addFavorite = async (
  id: string,
  options?: RequestInit
): Promise<addFavoriteResponse> => {
  return customFetch<addFavoriteResponse>(getAddFavoriteUrl(id), {
    ...options,
    method: 'POST',
  });
};

/**
 * Removes a listing from the authenticated user's favorites. Returns 404 if not favorited.
 * @summary Unfavorite a listing
 */
export type removeFavoriteResponse200 = {
  data: ApiResponse;
  status: 200;
};

export type removeFavoriteResponseSuccess = removeFavoriteResponse200 & {
  headers: Headers;
};
export type removeFavoriteResponse = removeFavoriteResponseSuccess;

export const getRemoveFavoriteUrl = (id: string) => {
  return `/listings/${id}/favorite`;
};

export const removeFavorite = async (
  id: string,
  options?: RequestInit
): Promise<removeFavoriteResponse> => {
  return customFetch<removeFavoriteResponse>(getRemoveFavoriteUrl(id), {
    ...options,
    method: 'DELETE',
  });
};

/**
 * Returns the authenticated user's profile information.
 * @summary Get current user profile
 */
export type getCurrentUserResponse200 = {
  data: UserResponse;
  status: 200;
};

export type getCurrentUserResponseSuccess = getCurrentUserResponse200 & {
  headers: Headers;
};
export type getCurrentUserResponse = getCurrentUserResponseSuccess;

export const getGetCurrentUserUrl = () => {
  return `/users/me`;
};

export const getCurrentUser = async (
  options?: RequestInit
): Promise<getCurrentUserResponse> => {
  return customFetch<getCurrentUserResponse>(getGetCurrentUserUrl(), {
    ...options,
    method: 'GET',
  });
};

/**
 * Partially updates the authenticated user's profile. Only provided fields are updated.
 * @summary Update current user profile
 */
export type updateCurrentUserResponse200 = {
  data: ApiResponse;
  status: 200;
};

export type updateCurrentUserResponseSuccess = updateCurrentUserResponse200 & {
  headers: Headers;
};
export type updateCurrentUserResponse = updateCurrentUserResponseSuccess;

export const getUpdateCurrentUserUrl = () => {
  return `/users/me`;
};

export const updateCurrentUser = async (
  userUpdateRequest: UserUpdateRequest,
  options?: RequestInit
): Promise<updateCurrentUserResponse> => {
  return customFetch<updateCurrentUserResponse>(getUpdateCurrentUserUrl(), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userUpdateRequest),
  });
};

/**
 * Returns full listing details including owner, property details, location, counters, and media.
 * @summary Get a listing by ID
 */
export type getListingByIdResponse200 = {
  data: ListingResponse;
  status: 200;
};

export type getListingByIdResponseSuccess = getListingByIdResponse200 & {
  headers: Headers;
};
export type getListingByIdResponse = getListingByIdResponseSuccess;

export const getGetListingByIdUrl = (id: string) => {
  return `/listings/${id}`;
};

export const getListingById = async (
  id: string,
  options?: RequestInit
): Promise<getListingByIdResponse> => {
  return customFetch<getListingByIdResponse>(getGetListingByIdUrl(id), {
    ...options,
    method: 'GET',
  });
};

/**
 * Soft-deletes a listing by setting status to archived. Only the owner can delete.
 * @summary Delete a listing
 */
export type deleteListingByIdResponse200 = {
  data: ApiResponse;
  status: 200;
};

export type deleteListingByIdResponseSuccess = deleteListingByIdResponse200 & {
  headers: Headers;
};
export type deleteListingByIdResponse = deleteListingByIdResponseSuccess;

export const getDeleteListingByIdUrl = (id: string) => {
  return `/listings/${id}`;
};

export const deleteListingById = async (
  id: string,
  options?: RequestInit
): Promise<deleteListingByIdResponse> => {
  return customFetch<deleteListingByIdResponse>(getDeleteListingByIdUrl(id), {
    ...options,
    method: 'DELETE',
  });
};

/**
 * Partially updates a listing. Only the owner can update. Tracks price history on price changes.
 * @summary Update a listing
 */
export type updateListingByIdResponse200 = {
  data: ApiResponse;
  status: 200;
};

export type updateListingByIdResponseSuccess = updateListingByIdResponse200 & {
  headers: Headers;
};
export type updateListingByIdResponse = updateListingByIdResponseSuccess;

export const getUpdateListingByIdUrl = (id: string) => {
  return `/listings/${id}`;
};

export const updateListingById = async (
  id: string,
  listingUpdateRequest: ListingUpdateRequest,
  options?: RequestInit
): Promise<updateListingByIdResponse> => {
  return customFetch<updateListingByIdResponse>(getUpdateListingByIdUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(listingUpdateRequest),
  });
};

/**
 * Generates a pre-signed S3 URL for downloading a file by its key.
 * @summary Get a pre-signed download URL
 */
export type getDownloadUrlResponse200 = {
  data: string;
  status: 200;
};

export type getDownloadUrlResponseSuccess = getDownloadUrlResponse200 & {
  headers: Headers;
};
export type getDownloadUrlResponse = getDownloadUrlResponseSuccess;

export const getGetDownloadUrlUrl = (params: GetDownloadUrlParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/s3/download-url?${stringifiedParams}`
    : `/s3/download-url`;
};

export const getDownloadUrl = async (
  params: GetDownloadUrlParams,
  options?: RequestInit
): Promise<getDownloadUrlResponse> => {
  return customFetch<getDownloadUrlResponse>(getGetDownloadUrlUrl(params), {
    ...options,
    method: 'GET',
  });
};

/**
 * Returns listings the authenticated user has saved for later.
 * @summary Get my saved listings
 */
export type getMySavedListingsResponse200 = {
  data: PageListingResponse;
  status: 200;
};

export type getMySavedListingsResponseSuccess =
  getMySavedListingsResponse200 & {
    headers: Headers;
  };
export type getMySavedListingsResponse = getMySavedListingsResponseSuccess;

export const getGetMySavedListingsUrl = (params: GetMySavedListingsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/listings/saved?${stringifiedParams}`
    : `/listings/saved`;
};

export const getMySavedListings = async (
  params: GetMySavedListingsParams,
  options?: RequestInit
): Promise<getMySavedListingsResponse> => {
  return customFetch<getMySavedListingsResponse>(
    getGetMySavedListingsUrl(params),
    {
      ...options,
      method: 'GET',
    }
  );
};

/**
 * Returns the authenticated user's own listings (excluding deleted).
 * @summary Get my listings
 */
export type getMyListingsResponse200 = {
  data: PageListingResponse;
  status: 200;
};

export type getMyListingsResponseSuccess = getMyListingsResponse200 & {
  headers: Headers;
};
export type getMyListingsResponse = getMyListingsResponseSuccess;

export const getGetMyListingsUrl = (params: GetMyListingsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/listings/my?${stringifiedParams}`
    : `/listings/my`;
};

export const getMyListings = async (
  params: GetMyListingsParams,
  options?: RequestInit
): Promise<getMyListingsResponse> => {
  return customFetch<getMyListingsResponse>(getGetMyListingsUrl(params), {
    ...options,
    method: 'GET',
  });
};

/**
 * Returns listings the authenticated user has favorited.
 * @summary Get my favorite listings
 */
export type getMyFavoritesResponse200 = {
  data: PageListingResponse;
  status: 200;
};

export type getMyFavoritesResponseSuccess = getMyFavoritesResponse200 & {
  headers: Headers;
};
export type getMyFavoritesResponse = getMyFavoritesResponseSuccess;

export const getGetMyFavoritesUrl = (params: GetMyFavoritesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/listings/favorites?${stringifiedParams}`
    : `/listings/favorites`;
};

export const getMyFavorites = async (
  params: GetMyFavoritesParams,
  options?: RequestInit
): Promise<getMyFavoritesResponse> => {
  return customFetch<getMyFavoritesResponse>(getGetMyFavoritesUrl(params), {
    ...options,
    method: 'GET',
  });
};

/**
 * Returns application health status.
 * @summary Health check
 */
export type healthResponse200 = {
  data: Health200;
  status: 200;
};

export type healthResponseSuccess = healthResponse200 & {
  headers: Headers;
};
export type healthResponse = healthResponseSuccess;

export const getHealthUrl = () => {
  return `/health`;
};

export const health = async (
  options?: RequestInit
): Promise<healthResponse> => {
  return customFetch<healthResponse>(getHealthUrl(), {
    ...options,
    method: 'GET',
  });
};

/**
 * Deletes a file from S3 by its key.
 * @summary Delete an S3 object
 */
export type deleteObjectResponse200 = {
  data: void;
  status: 200;
};

export type deleteObjectResponseSuccess = deleteObjectResponse200 & {
  headers: Headers;
};
export type deleteObjectResponse = deleteObjectResponseSuccess;

export const getDeleteObjectUrl = (params: DeleteObjectParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/s3?${stringifiedParams}` : `/s3`;
};

export const deleteObject = async (
  params: DeleteObjectParams,
  options?: RequestInit
): Promise<deleteObjectResponse> => {
  return customFetch<deleteObjectResponse>(getDeleteObjectUrl(params), {
    ...options,
    method: 'DELETE',
  });
};
