/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Standard API response for mutation operations
 */
export interface ApiResponse {
  /** Whether the operation succeeded */
  success?: boolean;
  /** Human-readable result message */
  message?: string;
}
