/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Listing engagement counters
 */
export interface Counters {
  viewCount?: number;
  favoriteCount?: number;
  saveCount?: number;
}
