/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type DetailsListingCondition =
  (typeof DetailsListingCondition)[keyof typeof DetailsListingCondition];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DetailsListingCondition = {
  brand_new: 'brand_new',
  used: 'used',
  renovated: 'renovated',
  under_construction: 'under_construction',
} as const;
