/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type DetailsFacingDirection =
  (typeof DetailsFacingDirection)[keyof typeof DetailsFacingDirection];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DetailsFacingDirection = {
  north: 'north',
  south: 'south',
  east: 'east',
  west: 'west',
} as const;
