/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DetailsListingCondition } from './detailsListingCondition';
import type { DetailsFacingDirection } from './detailsFacingDirection';

/**
 * Property detail specifications
 */
export interface Details {
  yearBuilt: number;
  listingCondition: DetailsListingCondition;
  facingDirection?: DetailsFacingDirection;
  bedroomsCount: number;
  bathroomsCount: number;
  balconiesCount: number;
  floorLevel?: number;
  furnished?: boolean;
  /** Number of parking spaces */
  parkingArea?: number;
  petFriendly?: boolean;
  /** Total lot area in sqft */
  lotArea?: number;
  /** Living area in sqft */
  livingArea: number;
}
