/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetDownloadUrlParams = {
  /**
   * S3 object key
   */
  key: string;
};
