/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ListingResponsePropertyStatus =
  (typeof ListingResponsePropertyStatus)[keyof typeof ListingResponsePropertyStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListingResponsePropertyStatus = {
  draft: 'draft',
  published: 'published',
  pending: 'pending',
  sold: 'sold',
  archived: 'archived',
} as const;
