/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ListingCreateRequestPropertyType =
  (typeof ListingCreateRequestPropertyType)[keyof typeof ListingCreateRequestPropertyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListingCreateRequestPropertyType = {
  house: 'house',
  apartment: 'apartment',
  studio: 'studio',
  condo: 'condo',
  penthouse: 'penthouse',
} as const;
