/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ListingCreateRequestPropertyType } from './listingCreateRequestPropertyType';
import type { Details } from './details';
import type { Location } from './location';
import type { MediaItem } from './mediaItem';

/**
 * Request body for creating a new property listing
 */
export interface ListingCreateRequest {
  /**
   * Listing title
   * @minLength 1
   */
  title: string;
  /** Detailed description of the property */
  description?: string;
  propertyType: ListingCreateRequestPropertyType;
  /** Asking price in BDT */
  pricing: number;
  details: Details;
  location: Location;
  /** List of media attachments (images/videos) */
  medias?: MediaItem[];
  /** If true, listing is published immediately; if false, saved as draft */
  isPublishing: boolean;
}
