/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ListingResponsePropertyType } from './listingResponsePropertyType';
import type { ListingResponsePropertyStatus } from './listingResponsePropertyStatus';
import type { Owner } from './owner';
import type { Details } from './details';
import type { Location } from './location';
import type { Counters } from './counters';
import type { Media } from './media';

/**
 * Full listing response with owner, property details, location, counters, and media
 */
export interface ListingResponse {
  /** Unique listing identifier */
  listingId?: string;
  /** Listing title */
  title?: string;
  /** Detailed description of the property */
  description?: string;
  propertyType?: ListingResponsePropertyType;
  propertyStatus?: ListingResponsePropertyStatus;
  /** Asking price in BDT */
  pricing?: number;
  owner?: Owner;
  details?: Details;
  location?: Location;
  counters?: Counters;
  media?: Media[];
  createdAt?: string;
  publishedAt?: string;
  updatedAt?: string;
}
