/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Change listing status (e.g. draft to published)
 */
export type ListingUpdateRequestPropertyStatus =
  (typeof ListingUpdateRequestPropertyStatus)[keyof typeof ListingUpdateRequestPropertyStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListingUpdateRequestPropertyStatus = {
  draft: 'draft',
  published: 'published',
  pending: 'pending',
  sold: 'sold',
  archived: 'archived',
} as const;
