/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ListingUpdateRequestPropertyType =
  (typeof ListingUpdateRequestPropertyType)[keyof typeof ListingUpdateRequestPropertyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListingUpdateRequestPropertyType = {
  house: 'house',
  apartment: 'apartment',
  studio: 'studio',
  condo: 'condo',
  penthouse: 'penthouse',
} as const;
