/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ListingUpdateRequestPropertyType } from './listingUpdateRequestPropertyType';
import type { ListingUpdateRequestPropertyStatus } from './listingUpdateRequestPropertyStatus';
import type { Details } from './details';
import type { Location } from './location';
import type { MediaItem } from './mediaItem';

/**
 * Request body for partially updating a listing. Only provided fields are updated.
 */
export interface ListingUpdateRequest {
  title?: string;
  description?: string;
  propertyType?: ListingUpdateRequestPropertyType;
  /** New asking price in BDT. Triggers price history tracking if changed. */
  pricing?: number;
  /** Change listing status (e.g. draft to published) */
  propertyStatus?: ListingUpdateRequestPropertyStatus;
  details?: Details;
  location?: Location;
  /** New or additional media attachments */
  mediaItems?: MediaItem[];
}
