/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Listing media attachment
 */
export interface Media {
  mediaId?: string;
  /** S3 pre-signed download URL */
  url?: string;
  /** MIME type */
  contentType?: string;
  /** Display order (0-based) */
  sortOrder?: number;
}
