/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Media attachment for the listing
 */
export interface MediaItem {
  /**
   * S3 object key returned from the upload endpoint
   * @minLength 1
   */
  s3Location: string;
  /**
   * MIME type
   * @minLength 1
   */
  contentType: string;
  /** Display order (0-based) */
  sortOrder: number;
  /** File size in bytes */
  byteSize: number;
  /** Optional caption for the media */
  caption?: string;
}
