/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Response containing a pre-signed S3 upload URL and the generated object key
 */
export interface MediaUploadResponse {
  /** Pre-signed S3 upload URL (PUT request) */
  uploadUrl?: string;
  /** S3 object key to reference this file later */
  key?: string;
}
