/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Request body for generating a pre-signed S3 upload URL
 */
export interface MediaUploadRequest {
  /**
   * Original file name
   * @minLength 1
   */
  fileName: string;
  /**
   * MIME type of the file
   * @minLength 1
   */
  contentType: string;
  /**
   * Upload category (used as S3 key prefix)
   * @minLength 1
   */
  category: string;
}
