/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Listing owner information
 */
export interface Owner {
  userId?: string;
  name?: string;
  /** S3 pre-signed URL for profile picture */
  profilePictureUrl?: string;
}
