/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * User profile information
 */
export interface UserResponse {
  userId?: string;
  name?: string;
  email?: string;
  phone?: string;
  /** Decrypted National ID */
  nid?: string;
  /** User role */
  roleName?: string;
  /** S3 pre-signed URL for profile picture */
  profilePictureUrl?: string;
  createdAt?: string;
}
