/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Request body for registering a new user
 */
export interface UserRegistrationRequest {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  email: string;
  phone?: string;
  /**
   * National ID number (will be encrypted)
   * @minLength 1
   */
  nid: string;
}
