/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Request body for partially updating user profile. Only provided fields are updated.
 */
export interface UserUpdateRequest {
  name?: string;
  phone?: string;
  /** National ID number (will be re-encrypted) */
  nid?: string;
  /** S3 object key for profile picture */
  profilePictureUrl?: string;
}
